In [2]:
import pandas as pd
import statsmodels.formula.api as sm

In [3]:
df = pd.read_csv('dataset_Facebook.csv')
df.head()

,Page_total_likes,Type,Post_Month,Post_Weekday,Post_Hour,Payment,Lifetime_Post_Total_Reach,Lifetime_Post_Total_Impressions,Lifetime_Engaged_Users,Lifetime_Post_Consumers,Lifetime_Post_Consumptions,Lifetime_Post_Impressions_by_people_who_have_liked_your_Page,Lifetime_Post_reach_by_people_who_like_your_Page,Lifetime_People_who_have_liked_your_Page_and_engaged_with_your_post,comment,like,share,Total_Interactions
0,139441,Photo,12,4,3,Not_Paid,2752,5091,178,109,159,3078,1640,119,4,79,17,100
1,139441,Status,12,3,10,Not_Paid,10460,19057,1457,1361,1674,11710,6112,1108,5,130,29,164
2,139441,Photo,12,3,3,Not_Paid,2413,4373,177,113,154,2812,1503,132,0,66,14,80
3,139441,Photo,12,2,10,Paid,50128,87991,2211,790,1119,61027,32048,1386,58,1572,147,1777
4,139441,Photo,12,2,3,Not_Paid,7244,13594,671,410,580,6228,3200,396,19,325,49,393

In [4]:
df_facebook_dummies = pd.get_dummies(df[['Type', 'Payment']])
df = pd.concat([df, df_facebook_dummies], axis = 1)
print(df)

     Page_total_likes    Type  Post_Month  Post_Weekday  Post_Hour   Payment  \
0              139441   Photo          12             4          3  Not_Paid
1              139441  Status          12             3         10  Not_Paid
2              139441   Photo          12             3          3  Not_Paid
3              139441   Photo          12             2         10      Paid
4              139441   Photo          12             2          3  Not_Paid
..                ...     ...         ...           ...        ...       ...
490             85093   Photo           1             7         10  Not_Paid
491             85093   Photo           1             7          2  Not_Paid
492             81370   Photo         100             5          8  Not_Paid
493             81370   Photo         100             5          2  Not_Paid
494             81370   Photo         100             4         11  Not_Paid

     Lifetime_Post_Total_Reach  Lifetime_Post_Total_Impressions  \
0                         2752                             5091
1                        10460                            19057
2                         2413                             4373
3                        50128                            87991
4                         7244                            13594
..                         ...                              ...
490                       5400                             9218
491                       4684                             7536
492                       3480                             6229
493                       3778                             7216
494                       4156                             7564

     Lifetime_Engaged_Users  Lifetime_Post_Consumers  ...  comment  like  \
0                       178                      109  ...        4    79
1                      1457                     1361  ...        5   130
2                       177                      113  ...        0    66
3                      2211                      790  ...       58  1572
4                       671                      410  ...       19   325
..                      ...                      ...  ...      ...   ...
490                     810                      756  ...       10   125
491                     733                      708  ...        5    53
492                     537                      508  ...        0    53
493                     625                      572  ...        4    93
494                     626                      574  ...        7    91

     share  Total_Interactions  Type_Link  Type_Photo  Type_Status  \
0       17                 100      False        True        False
1       29                 164      False       False         True
2       14                  80      False        True        False
3      147                1777      False        True        False
4       49                 393      False        True        False
..     ...                 ...        ...         ...          ...
490     41                 176      False        True        False
491     26                  84      False        True        False
492     22                  75      False        True        False
493     18                 115      False        True        False
494     38                 136      False        True        False

     Type_Video  Payment_Not_Paid  Payment_Paid
0         False              True         False
1         False              True         False
2         False              True         False
3         False             False          True
4         False              True         False
..          ...               ...           ...
490       False              True         False
491       False              True         False
492       False              True         False
493       False              True         False
494       False              True         False

[495 rows x 24 columns]

In [5]:
#Lifetime_Engaged_Users = df['Lifetime_Engaged_Users']
#Status = df['Status']
#Video = df['Video']
#Link = df['Link']
#Paid = df['Paid']
#Post_month = df['Post_month']
#Type = df['Type']

model1 = sm.ols('Lifetime_Engaged_Users~Type', data = df).fit() #idk man
print(model1.summary())

                              OLS Regression Results
==================================================================================
Dep. Variable:     Lifetime_Engaged_Users   R-squared:                       0.149
Model:                                OLS   Adj. R-squared:                  0.144
Method:                     Least Squares   F-statistic:                     28.69
Date:                    Tue, 26 Mar 2024   Prob (F-statistic):           4.15e-17
Time:                            16:15:28   Log-Likelihood:                -4075.1
No. Observations:                     495   AIC:                             8158.
Df Residuals:                         491   BIC:                             8175.
Df Model:                               3
Covariance Type:                nonrobust
==================================================================================
                     coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------
Intercept        342.8182    194.835      1.760      0.079     -39.996     725.632
Type[T.Photo]    482.5500    199.861      2.414      0.016      89.861     875.239
Type[T.Status]  1697.4040    237.738      7.140      0.000    1230.294    2164.514
Type[T.Video]   1364.1818    396.568      3.440      0.001     585.002    2143.362
==============================================================================
Omnibus:                      555.330   Durbin-Watson:                   1.713
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            45860.557
Skew:                           5.064   Prob(JB):                         0.00
Kurtosis:                      49.054   Cond. No.                         14.8
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

To check if data has missing values use: df.isnull().sum()
If you want to completly remove these values: df.dropna()
To create a dummy for missings: data_new = pd.get_dummies(data, dummy_na=True)

In [6]:
dfm = pd.read_csv('insurance_missings.csv')
dfm.head()

   age     sex    bmi  children smoker     region      charges
0   19  female  27.90         0    yes  southwest  16884.92400
1   31  female  25.74         0     no  southeast   3756.62160
2   60  female  25.84         0     no  northwest  28923.13692
3   62  female  26.29         0    yes  southeast  27808.72510
4   56  female  39.82         0     no  southeast  11090.71780

In [7]:
dfm.isnull().sum()
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

In [8]:
ds_missing_dummies = pd.get_dummies(dfm[['sex', 'smoker']])
dfm = pd.concat([dfm, ds_missing_dummies], axis = 1)

In [9]:
dfm.isnull().sum()

age             0
sex             0
bmi           197
children        0
smoker        106
region          0
charges         0
sex_female      0
sex_male        0
smoker_no       0
smoker_yes      0
dtype: int64

In [10]:
dfm_new = pd.get_dummies(dfm, dummy_na=True)
imputed_data = IterativeImputer().fit_transform(dfm_new)

In [11]:
dfm_new.head()

,age,bmi,children,charges,sex_female,sex_male,smoker_no,smoker_yes,sex_female,sex_male,sex_nan,smoker_no,smoker_yes,smoker_nan,region_northeast,region_northwest,region_southeast,region_southwest,region_nan
0,19,27.90,0,16884.92400,True,False,False,True,True,False,False,False,True,False,False,False,False,True,False
1,31,25.74,0,3756.62160,True,False,True,False,True,False,False,True,False,False,False,False,True,False,False
2,60,25.84,0,28923.13692,True,False,True,False,True,False,False,True,False,False,False,True,False,False,False
3,62,26.29,0,27808.72510,True,False,False,True,True,False,False,False,True,False,False,False,True,False,False
4,56,39.82,0,11090.71780,True,False,True,False,True,False,False,True,False,False,False,False,True,False,False

In [12]:
#ds_missing_dummies_new = pd.get_dummies(dfm_new[['sex', 'smoker']])
#dfm_new = pd.concat([dfm, ds_missing_dummies_new], axis = 1)

#i dont think i need these as dfm_new was already based on a set that used dummies

KeyError: "None of [Index(['sex', 'smoker'], dtype='object')] are in the [columns]"

In [14]:
imputed_data = pd.DataFrame(imputed_data, columns=dfm_new.columns)

In [16]:
model2 = sm.ols('charges~age + sex + bmi + children + smoker_yes + smoker_no', data=dfm).fit()
print(model2.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                charges   R-squared:                       0.712
Model:                            OLS   Adj. R-squared:                  0.711
Method:                 Least Squares   F-statistic:                     467.9
Date:                Tue, 26 Mar 2024   Prob (F-statistic):          1.41e-302
Time:                        16:17:50   Log-Likelihood:                -11664.
No. Observations:                1141   AIC:                         2.334e+04
Df Residuals:                    1134   BIC:                         2.338e+04
Df Model:                           6
Covariance Type:            nonrobust
======================================================================================
                         coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------
Intercept          -6253.6648   1342.065     -4.660      0.000   -8886.874   -3620.456
sex[T.male]         -284.0739    401.609     -0.707      0.480   -1072.054     503.906
smoker_yes[T.True]  1.899e+04    853.343     22.255      0.000    1.73e+04    2.07e+04
smoker_no[T.True]  -5601.8651    756.444     -7.406      0.000   -7086.052   -4117.678
age                  264.5201     14.173     18.664      0.000     236.712     292.328
bmi                  309.7063     32.384      9.564      0.000     246.167     373.246
children             495.1647    168.251      2.943      0.003     165.047     825.283
==============================================================================
Omnibus:                      262.055   Durbin-Watson:                   1.902
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              626.064
Skew:                           1.232   Prob(JB):                    1.13e-136
Kurtosis:                       5.664   Cond. No.                         394.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [17]:
model2_new = sm.ols('charges~age + sex + bmi + children + smoker', data=dfm_new).fit()
print(model2_new.summary())

PatsyError: categorical data cannot be >1-dimensional